require: rubocop-rails

Metrics/AbcSize:
  Max: 20
  Exclude:
  - 'app/models/user.rb'

Metrics/ClassLength:
  Exclude:
  - 'test/models/company_test.rb'

Layout/LineLength:
  Max: 120
  Exclude:
  - 'config/initializers/devise.rb'
  - 'app/models/user.rb'

Metrics/BlockLength:
  Exclude:
  - 'db/schema.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
  - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Enabled: false
  
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: single_quotes
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'app/controllers/devise/registrations_controller.rb'
    - 'vendor/**/*'
