language: ruby
rvm:
 - 2.5.1

#------------------------------
# Setup
  
before_script:
 - nvm install node
 - bundle exec rails webpacker:install
 - RAILS_ENV=test bundle exec rails webpacker:compile
