language: ruby
rvm:
 - 2.7.0

services:
  - postgresql

#------------------------------
# Setup

install: bundle install --jobs=3 --retry=3

before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - cp config/database.yml.travis config/database.yml
 - export DEVISE_SECRET=$(rake secret)
 - nvm install node
 - bundle exec rails webpacker:install
 - RAILS_ENV=test bundle exec rails webpacker:compile
 - find ./vendor -name .rubocop.yml -delete
